server:
  port: 8071

spring:
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
            '[/**]':
              allowedOrigins: "http://localhost:4200"
              allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              allowHeaders:
              - "*"
            

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://eurekaserver-ms:8070/eureka/


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true
