server:
  port: 8071

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:7070/realms/tfg
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
            '[/**]':
              allowedOrigins: "http://localhost:4200"
              allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              allowedHeaders:
              - "*"
  
            

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true
