server:
  port: 8081

spring:
    datasource:
        url: jdbc:mysql://192.168.1.36:3307/inventariodb
        username: root
        password: "root"
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        hibernate:
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
            ddl-auto: update
            
        show-sql: true
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB
    cloud:
        function:
            definition: sendInventarioConfirmation
        stream:
          bindings:
            sendInventarioConfirmation-in-0:
              destination: inventario-confirmation
          kafka:
            binder:
              brokers: 
                - 192.168.1.36:9092
eureka:
  instance:
    preferIpAddress: false
    hostname: inventario-container
  client:
    serviceUrl:
      defaultZone: http://eurekaserver-container:8070/eureka/
