server:
  port: 8081

spring:
  datasource:
        url: jdbc:mysql://localhost:3307/inventariodb
        username: root
        password: root
    jpa:
        hibernate:
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        show-sql: true
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB

info:
  app:
    version: "1.0.0"
    message: "Desarrollando el microservicio de inventario"
    contact:
      name: "Alberto"
      email: "alberto@example.com"
