server:
    port: 9090
spring:
    datasource:
        url: jdbc:mysql://pagos-db-ms:3309/transacciones
        username: root
        password: "root"
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        hibernate:
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        show-sql: true
    cloud:
      function:
        definition: sendPagoConfirmation
      stream:
        bindings:
          sendPagoConfirmation-out-0:
            destination: pago-confirmation
        kafka:
          binder:
            brokers:
              - localhost:9092
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate: 
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
