server:
    port: 8082

spring:
    datasource:
        url: jdbc:mysql://localhost:3308/reservasdb
        username: root
        password: "root"

    jpa:
        hibernate:
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        show-sql: true
