server:
    port: 8082

spring:
    datasource:
        url: jdbc:mysql://192.168.1.36:3308/reservasdb
        username: root
        password: "root"
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        hibernate:
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
            ddl-auto: update
        show-sql: true
    cloud:
        function:
            definition: sendEmail;sendInventarioConfirmation;sendPagoConfirmation

        stream:
          bindings:
            sendEmail-out-0:
              destination: send-email
            sendInventarioConfirmation-out-0:
              destination: inventario-confirmation
            sendPagoConfirmation-in-0:
              destination: pago-confirmation
            
          kafka:
            binder:
              brokers: 
                - 192.168.1.36:9092
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
        defaultZone: http://192.168.1.36:8070/eureka/
