server:
  port: 8085

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/usuariosdb
        username: root
        password: root
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
