server:
  port: 8085

spring:
    datasource:
        url: jdbc:mysql://usuarios-db-ms:3306/usuariosdb
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
